In [2]:
# Librerias y dependencias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.linear_model import LassoCV
from numpy import mean
from numpy import std
from numpy import arange
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import f1_score, accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
import sys
import random

In [34]:
'''
    Esta clase permite realizar la codificación en caliente especificameente variables categoricas
'''

class OneHotCoding():
    def __init__(self, df, bin_features):
        self.bin_features = bin_features
        self.df = df
    
    # Metodo para realizar la codificacion dummy a las variables categoricas

    def dummyCodification(self):
        cat_features = self.df.select_dtypes(include = ["object", "category"]).columns
        bin_dataset = self.df[self.bin_features].replace({'SI': 1, 'NO': 0})
        categorical_features = [x for x in cat_features if x not in self.bin_features]
        df_cat = pd.get_dummies(self.df[categorical_features],dtype=int)
        self.df.drop(cat_features, axis = 1, inplace = True)
        df_final = pd.concat([self.df,df_cat,bin_dataset ], axis = 1)
        df_final.to_excel("../Archivos Generados/PipelineResults/dasetOneHot.xlsx")
        print("Ejeción Terminada")
        return df_final


#categorical_transformer = Pipeline(
#    steps=[("OneHotCoding",  OneHotCoding(df,bin_features).dummyCodification())]
#)


class LinearRegession():
    def __init__(self, df, alpha, l1_ratio):
        self.df = df
        self.alpha = alpha
        self.l1_ratio = l1_ratio
    

    def CalcularModeloLR(self):
        # alpha=0.1, l1_ratio=0.97
        Y = self.df.RDT_AJUSTADO.values
        X = self.df.drop(["RDT_AJUSTADO","ID_LOTE"], axis=1).values
        #print("Longitud X: ", X.shape) 
        modelElasticNet = ElasticNet(alpha=self.alpha, l1_ratio=self.l1_ratio, random_state=123)
        model = modelElasticNet.fit(X,Y)
        r_2 = model.score(X,Y)
        # Pedicciones
        yhat = model.predict(X)

        return [model, r_2, yhat]


class CLR():

    def __init__(self, df, yhat):
        self.df = df
        self.yhat = yhat

    
    def calcularMAE(self):
        contador=0
        EPA = 0
        Acumulador = 0
        accepted_average_error= []
        self.df["yhat"]= pd.Series(self.yhat)
        self.df["EA"] = abs(self.df.RDT_AJUSTADO - self.df.yhat)
        self.df_ordely = self.df.sort_values(by=['EA'],ascending=True).reset_index()

        # Calculamos el MAE
        for i in range(len(self.df_ordely)):
            Acumulador = Acumulador + self.df_ordely.loc[i].EA
            EPA = Acumulador/(i+1)
            accepted_average_error.append(EPA)
        
        # Agregamos el promedio al dataset Ordenado.
        self.df_ordely["MAE"] = pd.Series(accepted_average_error)
        #self.df_ordely.to_excel(f"FASE1/DatasetOrdenadoIteraciónesss{contador +1}.xlsx")
        #self.df.to_excel("../Archivos Generados/PipelineResults/DatasetOriginal.xlsx")
        contador=contador+1
        return self.df_ordely
    


def DeleteRecordsGroup(Group, df):
    indexEliminar = list(Group["index"])
    df_new = df[df.index.isin(indexEliminar)== False]
    return df_new


# Retorna el grupo a modificar
def compareCorrelation(CorelacionGruposCalidad, nuevaCorrelation, listaGrupos):
    lista_grupos = listaGrupos
    #print("lista grupos: ",lista_grupos)
    arr =  np.array(CorelacionGruposCalidad) - np.array(nuevaCorrelation)
    position = np.where(arr == np.amin(arr))
    #print("Posision grupo: ",position)
    indexGrupoModificar = position[0][0]
    #print("index: ", indexGrupoModificar)
    lista_grupos.pop(indexGrupoModificar)
    return lista_grupos, indexGrupoModificar


def dataframeNormalized(dataset):
    Y = dataset.RDT_AJUSTADO
    X = dataset.drop(["RDT_AJUSTADO"], axis=1)
    # Nombre columnas de X[Variables independientes]
    X_name_columns= X.columns
    scaler = MinMaxScaler()
    X_normalized = scaler.fit_transform(X.values)
    df_X_normalized = pd.DataFrame(X_normalized, columns= X_name_columns)
    df_normalized = pd.concat([df_X_normalized, Y], axis=1)
    print(df_normalized.shape)
    return df_normalized



# Funcion para Normalizar la Vista minable a exepción de la etiqueta(Variable Objetivo)
def EncoderViewMinable(df):
    new_dataset = df
    norm = MinMaxScaler()
    norm = norm.fit(new_dataset.values[:,:])
    valMin = norm.data_min_
    valMax = norm.data_max_
    dataRange = norm.data_range_
    #df_norm = norm.fit_transform(df.values[:,:-1])

    return [valMin, valMax, dataRange]


def fase1(dataset,Minimum_records,minimum_correlation, MAE_Allowed,additional_average_error):
    group_acepted = []
    correlation_model =[]
    model_acepted = []
    contador = 0
    while (len(dataset) !=0):
        contador = contador+ 1
        print("Tamaño del dataset: ", dataset.shape)
        modellr, r_2, yhat = LinearRegession(dataset, 0.1, 0.97).CalcularModeloLR()
        print("Ajuste del Modelo dataset Completo: ", r_2)
        DatasetOrdely = CLR(dataset,yhat).calcularMAE()
        #DatasetOrdely.to_excel(f"FASE1/DatasetOrdenado{contador}.xlsx")

        try:
            group = DatasetOrdely.loc[DatasetOrdely.MAE < MAE_Allowed]
        except:
             print(f"No se cumple con el criterio de selección, verificar variable MAE_ALLOWED: {MAE_Allowed}")
             # Retornar variables vacias
             break

        print(f"Longitud de grupo {contador}: ", len(group))
        if (len(group) >= Minimum_records):
                print("El grupo cumple minimo de registros")
                group = group.drop(["yhat","EA","MAE"], axis=1)
                dataset = dataset .drop(["yhat","EA"], axis=1)
                group_model, r2_group_mode, yhat_group = LinearRegession(group,0.1,0.97).CalcularModeloLR()
                print(f"R2 del grupo {contador}: ",r2_group_mode)
                if(r2_group_mode >= minimum_correlation):
                    # Elimino los registros para la siguiente iteración
                    dataset = DeleteRecordsGroup(group, dataset)
                    group = group.drop(['index'], axis=1)
                    group_acepted.append(group)
                    model_acepted.append(group_model)
                    correlation_model.append(r2_group_mode)
                    group.to_excel(f"FASE1/GrupoN_{contador}.xlsx")
                    MAE_Allowed = MAE_Allowed + additional_average_error
                else:
                    print("No cumple con la condición de  la correlacion")
                    Orphans = dataset
                    # Se eliminan las variables de trtamiento [yhat, EA]
                    Orphans = Orphans.drop(["yhat", "EA"],axis=1).reset_index(drop=True)
                    print("Logitud Huerfanos: ", Orphans.shape)
                    break  
        else:

            Orphans = dataset
            # Se eliminan las variables de trtamiento [yhat, EA]
            Orphans = Orphans.drop(["yhat", "EA"],axis=1).reset_index(drop=True)
            print("Logitud Huerfanos: ", Orphans.shape)
            # Se guardan los huerfanos en un archivo.
            Orphans.to_excel("FASE1/HuerfanosN.xlsx")
            break
    
    return [group_acepted, model_acepted, correlation_model, Orphans]



def fase2(group_acepted, correlation_model, Orphans):
    # Variables de entrada
    quality_groups = group_acepted.copy()
    correlation_quality_groups = correlation_model.copy()
    new_correlation = []

    group_list = list(range(len(quality_groups)))
    for register in range(len(Orphans)):
        for group in range(len(quality_groups)):
            quality_groups[group] = pd.concat([Orphans.loc[[0]], quality_groups[group]],ignore_index=True)        
            new_model, new_r2, new_yhat = LinearRegession(quality_groups[group],0.1, 0.97).CalcularModeloLR()
            new_correlation.append(new_r2)

        # Compración de las correlaciones
        list_groups_remove, index = compareCorrelation(correlation_quality_groups, new_correlation, group_list)
        #print(f"Grupos Eliminar registro: {list_groups_remove} y indeice del grupo a amntener registro {index}")
        correlation_quality_groups[index] = new_correlation[index]
        new_correlation = []
        group_list = list(range(len(quality_groups)))

        # Eliminacion de Regristro en los demas grupos
        for i in list_groups_remove:
            quality_groups[i].drop([0],axis=0, inplace=True)

        Orphans.drop([0],axis=0, inplace=True)
        Orphans = Orphans.reset_index(drop=True)

    return [quality_groups,correlation_quality_groups, Orphans]




#  Funciones Improvisación
#===================================================================================================

# Construir grupos de Calidad
def BuildGroupsQuality(definitive_groups):
    for i in range(len(definitive_groups)):
        definitive_groups[i]["Grupo"]= (i)

    df = pd.concat(definitive_groups, ignore_index=True)
    df = df.drop(["ID_LOTE"], axis=1)
    return df



'''
Funcion para generar el vector de pesos aleatorio.
Entradas:
w: Vector de pesos w [0,1], igual al numero de caracteristicas normalizadas.
nc: Nunero de ceros que debe contener el vector de pesos [10,20,30,40,50]
'''
def GenerateWeightVector(size):
    w = np.random.uniform(low=0, high=1, size=(size))
    sum = w.sum()
    w = w / sum

    return w



'''
-Función de calidad, que retorna la metrica de calidad asociada a ese vector w especifico
-Se debe tener en cunata la seleccion de la metrica de calidad asociada, para evaluar
el desempeño del algoritmo (Problema de Clasificacion)
Entradas:
    df_norm: Dataset Normalizado.
    wi: Vector de Pesos.
'''

'''
# Dependiendo del vector de pesos me extrae el acuracy - F1 score
def qualityFunction(df_norm, wi,df):
    #print("longitud df_norm: ",len(df_norm))
    #print("Longitud wi: ", len(wi))
    y_pred = []
    for i in range(len(df_norm)):
        vrf = df_norm[i] 
        minDep = sys.float_info.max
        posMinDep = 0
        for j in range(len(df_norm)):
            if i != j:
                ri = wi* np.power((df_norm[j] - vrf), 2)
                dE = np.sum(ri)
                if dE < minDep:
                    posMinDep=j
                    minDep = dE
        #print(posMinDep)
        y_pred.append(df.values[posMinDep][-1])
    qs = accuracy_score(list(df.values[:,-1]), y_pred)
    return qs
'''



# Dependiendo del vector de pesos me extrae el acuracy - F1 score

# df: Datasaset distancia que incluye los atributos con los grupos
def qualityFunction(df_norm, wi,df, lista_modelos, limites_15):
    #print("longitud df_norm: ",len(df_norm))
    #print("Longitud wi: ", len(wi))
    y_pred = []
    for i in range(len(df_norm)):
        vrf = df_norm[i] 
        minDep = sys.float_info.max
        posMinDep = 0
        for j in range(len(df_norm)):
            if i != j:
                ri = wi* np.power((df_norm[j] - vrf), 2)
                dE = np.sum(ri)
                if dE < minDep:
                    posMinDep=j
                    minDep = dE
        print(posMinDep)
        modelo = df.values[posMinDep][-1]
        print("Modelo: ", modelo)
        # caculamos la predicción de c/d registro con el modelo seleccionado
        y_pred = lista_modelos[modelo].predict(df.values[:,:-1][i].reshape(1,-1))[0]
        
        if (y_pred >= limites_15.values[i][2]) & (y_pred <= limites_15.values[i][2]):
            contador = contador + 1
        
    qs = contador/len(df_norm)
    print("Calidad: ", qs)
    return qs



'''
Función para generar la memoria Armonica
Entradas:
    MAC: Tamaño de la  Memoria Armonica
    wi: Vector de Pesos.
    nc: Numero de ceros (Selección de atributos)
'''

def GenerateArmonyMemory(df_norm, MAC,df,lista_modelos, limites_15):
    Lw = []
    for i in range (MAC):
        wi = GenerateWeightVector(174)
        Qs = qualityFunction(df_norm, wi,df,lista_modelos, limites_15)
        wiq = np.append(wi, Qs)
        Lw.append(wiq)

    
    Lw.sort(key=lambda x: x[-1], reverse=True)
    return Lw



def ImprovisationGBHS(PAR, hmn, nc,dataset_normalizado , lmp, HMRC,df,lista_modelos, limites_15):

    df_norm = dataset_normalizado

    # Se genera la memoria Armonica - diferentes tamaños
    np.random.seed(123)
    MA = GenerateArmonyMemory(df_norm,hmn,df,lista_modelos, limites_15)
    P=len(MA[0]) 
    
    
    curvaFitnes = []
    vectorIteration= []
    for i in range (lmp):
        pesosAleatorios = np.random.rand(P-1)
        for j in range(P-1):
            Aleatorio1 = random.random() 
            if (Aleatorio1 < HMRC):
                pma = random.randint(0, hmn-1)
                pesosAleatorios[j]= MA[pma][j]

                Aleatorio2 = random.random()
                if Aleatorio2 < PAR:
                    pesosAleatorios[j] = MA[0][j]
            
            else:
                Aleatorio3 = random.random()
                if Aleatorio3 < nc/P:
                    Aleatorio4 = 0
                else:
                    Aleatorio4 = Aleatorio3/(P-nc)
                
                pesosAleatorios[j] = Aleatorio4
        

        # Normalización de los pesos
        wf = GenerateWeightVector(pesosAleatorios, 0)
        fitnes = qualityFunction(df_norm, wf,df)



        # Remplazo
        if MA[hmn -1][P-1] < fitnes:
            new_register = np.append(wf, fitnes)
            MA[hmn-1] = new_register
            #print("------------------------------------")
            MA.sort(key=lambda x: x[-1], reverse=True)
        

        
        curvaFitnes.append(MA[0][P-1])
        vectorIteration.append(MA[0])
        

    
    
    print("Valor de la curva en la ultima poisción: ",curvaFitnes[-1])
    '''
    dicc = {"vector":vectorIteration,
                "Fitnes": curvaFitnes}
    

    df_new = pd.DataFrame(data=dicc)
    df_new.to_csv(f"ResultadosImprovisacion/GBHS.csv")
    dicc = dict()
    '''
    return [curvaFitnes[-1], vectorIteration[-1]]


# Funcion para Normalizar la Vista minable a exepción de la etiqueta(Variable Objetivo)
# df: es la matriz df.values [] , no incluye la etiqueta del grupo
def NormalizeViewMinable(df,valMin, dataRange):
    dataset_normalizado = np.empty((df.shape[0], df.shape[1]))
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            dataset_normalizado[i][j]= (df[i][j] - valMin[j])/dataRange[j]

    return dataset_normalizado




def predictionTest(dataset_test_norm, df_norm, vector_pesos_optmizacion, final_datset_join, list_final_models,dataset_validation):
    df_groups_finally = df_norm.copy()
    minDep = sys.float_info.max
    lista_asignacion_grupos = []
    print("Longitud dataset norm: ",dataset_test_norm.shape[0])
    print("Vista minable : ",df_groups_finally.shape[0])
    posMinDep = 0
    y_pred_test = []
    for z in range(int(dataset_test_norm.shape[0])):
        for k in range(int(df_groups_finally.shape[0])):
            ri = vector_pesos_optmizacion * np.power((dataset_test_norm[z]- df_groups_finally[k]),2) 
            dE = np.sum(ri)
            if dE < minDep:
                posMinDep = k
                minDep=dE
        
        #print("zz, " , z)
        # Grupo seleccionado
        grupoSelected = int(final_datset_join.values[posMinDep][-1])
        lista_asignacion_grupos.append(grupoSelected)   
        #print(grupoSelected)
        #model_final, r2_final, yhat_final = LinearRegession(definitive_groups[i],0.1, 0.97).CalcularModeloLR() 
        psi_predicho = list_final_models[grupoSelected].predict(dataset_validation.values[z].reshape(1,-1))
        #print(psi_predicho)
        y_pred_test.append(psi_predicho[0])

    return [y_pred_test,lista_asignacion_grupos]



def metricasPerformanceCLR(y_true, yhat_test):

    R2 = r2_score(y_true, yhat_test)
    MAE =  mean_absolute_error(y_true, yhat_test)
    print(R2)
    print(MAE)

In [5]:

# Variables Globales
# ==============================================================================
Minimum_records = 64
minimum_correlation= 0.88
MAE_Allowed = 143                                                         #MAE
additional_average_error = 98
contador = 0
definitive_groups = []

#1. Lectura del Dataset Principal
# ==============================================================================

#df = pd.read_excel("../Data/Gold/DatasetFinal.xlsx")
df = pd.read_csv("../Data/Gold/DatasetFinalFP.csv")
#print(df.head())
# Ornial variables list
bin_features =['SEM_TRATADAS','DRENAJE','ALMACENAMIENTO_FINCA','CAP_ENDURE_RASTA','MOTEADOS_RASTA','MOTEADOS_MAS70cm._RASTA',
               'OBSERVA_EROSION_RASTA','OBSERVA_MOHO_RASTA','OBSERVA_RAICES_VIVAS_RASTA','OBSERVA_HOJARASCA_MO_RASTA',
                'SUELO_NEGRO_BLANDO_RASTA','CUCHILLO_PRIMER_HTE_RASTA','CERCA_RIOS_QUEBRADAS_RASTA',
               ]


#2. Codificación de variables categoricas - Dummy
# ============================================================
dataset = OneHotCoding(df,bin_features).dummyCodification()
print("Dimension dataset Original: ", dataset.shape)

dataset_original = dataset.copy()
dataset_vindep = dataset.copy()
dataset_vindep= dataset_vindep.drop(["RDT_AJUSTADO","ID_LOTE"],axis=1)



#2. Encoders [Min, Max, data Range] para aplicar data Normalization
# =================================================================
'''
    Entradas: dataset: vista minable de caracteristicas indepenedientes, exepto la V objetivo
'''
valMin, valMax, dataRange = EncoderViewMinable(dataset_vindep)
print("Longitudes : ", len(valMin), len(valMax), len(dataRange))
# Guardamos los encoders apra posteriores usos
np.savetxt('FASE2/Encoder_ValMin.txt', valMin)
np.savetxt('FASE2/Encoder_dataRange.txt', dataRange)


#3. División de datset Training and Test
# ============================================================
dataset_train, dataset_test = train_test_split(dataset, test_size = 0.1, random_state=92)
print("Longitud Dataset Entrenamiento:",  dataset_train.shape)
dataset_training = dataset_train.copy()


# 4. Construcción de grupos de CalidaD FASE 1
# ============================================================
group_acepted, model_acepted, correlation_model, Orphans = fase1(dataset_training, Minimum_records,minimum_correlation, MAE_Allowed,additional_average_error)
print("---------------- FASE 1---------------------")
print("Correlaciones Iniciales: ", correlation_model)
#print(f"Grupo 1 {len(group_acepted[0])}, Grupo 2: {len(group_acepted[1])}, Grupo 3: {len(group_acepted[2])}")
print("Huerfanos: ", Orphans.shape)


# 5. Construccción de grupos definitivos 
# ============================================================

if len(group_acepted) > 1:
    if len(Orphans) == 0:
        definitive_groups = group_acepted
    
    else:
        # Fase 2, incluir los huerfanos
        print("FASE 2")
        quality_groups, correlation_quality_groups, orphans = fase2(group_acepted,correlation_model, Orphans)
        print("------------------ FASE 2 -------------------")
        print("Correlaciones Finales: ", correlation_quality_groups)
        #print(f"Grupo 1 {len(quality_groups[0])}, Grupo 2: {len(quality_groups[1])}, Grupo 3: {len(quality_groups[2])}")
        print("Huerfanos: ", orphans.shape)
        # Guardamos los grupos Finales
        for c, g in enumerate (quality_groups):
            print(f"Longitud Grupo {c} :  {len(quality_groups[c])} ")
            g.to_excel(f"FASE2/grupo_N{c}.xlsx")
   
        
        for c, value in enumerate (correlation_quality_groups):
            if value < 0.88:
                dataset_group = quality_groups[c]
                # Se aplica el mismo proceso que la fase 1
                group_acepted2, model_acepted2, correlation_model2, Orphans2 = fase1(dataset_group ,Minimum_records,minimum_correlation, MAE_Allowed,additional_average_error)
            else:
                definitive_groups.append(quality_groups[c])


        # Aqui va el proceso de Afinamieno e improvisación 
        
else:
    definitive_groups = Orphans


print("Grupos Definitivos: ", len(definitive_groups))

# Modelos Finales
list_final_models = []
for i in range(len(definitive_groups)):
    model_final, r2_final, yhat_final = LinearRegession(definitive_groups[i],0.1, 0.97).CalcularModeloLR()
    print("R2: ", r2_final)
    list_final_models.append(model_final)
    


grupos_finales = definitive_groups.copy()

C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bin_dataset = self.df[self.bin_features].replace({'SI': 1, 'NO': 0})
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:19: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  df_final.to_excel("../Archivos Generados/PipelineResults/dasetOneHot.xlsx")

Ejeción Terminada
Dimension dataset Original:  (799, 176)
Longitudes :  174 174 174
Longitud Dataset Entrenamiento: (719, 176)
Tamaño del dataset:  (719, 176)
Ajuste del Modelo dataset Completo:  0.7353483834467243

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+07, tolerance: 1.352e+05
  model = cd_fast.enet_coordinate_descent(

Longitud de grupo 1:  82
El grupo cumple minimo de registros
R2 del grupo 1:  0.9836604206704304

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.014e+06, tolerance: 8.108e+03
  model = cd_fast.enet_coordinate_descent(
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:161: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  group.to_excel(f"FASE1/GrupoN_{contador}.xlsx")

Tamaño del dataset:  (637, 176)
Ajuste del Modelo dataset Completo:  0.7579266531777857

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.259e+07, tolerance: 1.271e+05
  model = cd_fast.enet_coordinate_descent(

Longitud de grupo 2:  103
El grupo cumple minimo de registros
R2 del grupo 2:  0.9693664058181423

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.409e+06, tolerance: 8.064e+03
  model = cd_fast.enet_coordinate_descent(
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:161: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  group.to_excel(f"FASE1/GrupoN_{contador}.xlsx")

Tamaño del dataset:  (534, 176)
Ajuste del Modelo dataset Completo:  0.7885999797900995

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.785e+07, tolerance: 1.188e+05
  model = cd_fast.enet_coordinate_descent(

Longitud de grupo 3:  97
El grupo cumple minimo de registros
R2 del grupo 3:  0.9693428877426256

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.126e+06, tolerance: 1.243e+04
  model = cd_fast.enet_coordinate_descent(
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:161: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  group.to_excel(f"FASE1/GrupoN_{contador}.xlsx")

Tamaño del dataset:  (437, 176)

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.323e+06, tolerance: 1.059e+05
  model = cd_fast.enet_coordinate_descent(

Ajuste del Modelo dataset Completo:  0.8086733922219101
Longitud de grupo 4:  65
El grupo cumple minimo de registros

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.531e+05, tolerance: 1.068e+04
  model = cd_fast.enet_coordinate_descent(
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:161: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  group.to_excel(f"FASE1/GrupoN_{contador}.xlsx")

R2 del grupo 4:  0.9986926562798951
Tamaño del dataset:  (372, 176)
Ajuste del Modelo dataset Completo:  0.8219141342617343

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.176e+06, tolerance: 9.375e+04
  model = cd_fast.enet_coordinate_descent(
C:\Users\germanm\AppData\Local\Temp\ipykernel_14844\1125052729.py:177: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  Orphans.to_excel("FASE1/HuerfanosN.xlsx")

Longitud de grupo 5:  37
Logitud Huerfanos:  (372, 176)
---------------- FASE 1---------------------
Correlaciones Iniciales:  [0.9836604206704304, 0.9693664058181423, 0.9693428877426256, 0.9986926562798951]
Huerfanos:  (372, 176)
FASE 2

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.321e+06, tolerance: 9.059e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.330e+06, tolerance: 9.129e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.367e+06, tolerance: 1.351e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.652e+05, tolerance: 1.189e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.206e+06, tolerance: 8.135e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.817e+06, tolerance: 8.111e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.413e+06, tolerance: 1.355e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.325e+05, tolerance: 1.076e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.223e+06, tolerance: 8.698e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.794e+06, tolerance: 8.744e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.460e+06, tolerance: 1.418e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.646e+05, tolerance: 1.155e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.355e+06, tolerance: 8.114e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.732e+06, tolerance: 8.064e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.581e+06, tolerance: 1.418e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.436e+05, tolerance: 1.077e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.207e+06, tolerance: 8.230e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.596e+06, tolerance: 8.150e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.524e+06, tolerance: 1.427e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.862e+05, tolerance: 1.082e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.280e+06, tolerance: 8.180e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.557e+06, tolerance: 8.109e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.479e+06, tolerance: 1.423e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.951e+05, tolerance: 1.084e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.221e+06, tolerance: 8.118e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.596e+06, tolerance: 8.088e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.476e+06, tolerance: 1.420e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.816e+05, tolerance: 1.089e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.333e+06, tolerance: 8.829e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.014e+06, tolerance: 8.884e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.955e+06, tolerance: 1.499e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.113e+05, tolerance: 1.179e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.292e+06, tolerance: 8.110e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.592e+06, tolerance: 8.073e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.492e+06, tolerance: 1.420e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.320e+05, tolerance: 1.181e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.856e+06, tolerance: 8.150e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.594e+06, tolerance: 8.132e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.555e+06, tolerance: 1.426e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.425e+05, tolerance: 1.191e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.379e+06, tolerance: 8.270e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.596e+06, tolerance: 8.184e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.510e+06, tolerance: 1.433e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.341e+05, tolerance: 1.200e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.537e+06, tolerance: 8.114e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.617e+06, tolerance: 8.064e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.599e+06, tolerance: 1.433e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.869e+05, tolerance: 1.191e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.810e+06, tolerance: 8.470e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.623e+06, tolerance: 8.496e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.622e+06, tolerance: 1.475e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.023e+05, tolerance: 1.241e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.208e+06, tolerance: 8.491e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.605e+06, tolerance: 8.382e+03
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.636e+06, tolerance: 1.509e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.657e+05, tolerance: 1.217e+04
  model = cd_fast.enet_coordinate_descent(

------------------ FASE 2 -------------------
Correlaciones Finales:  [0.9725819476985545, 0.9747155427618888, 0.9630098339827987, 0.9707201560468381]
Huerfanos:  (0, 176)
Longitud Grupo 0 :  161
Longitud Grupo 1 :  195
Longitud Grupo 2 :  204
Longitud Grupo 3 :  159
Grupos Definitivos:  4
R2:  0.9725819476985545
R2:  0.9747155427618888
R2:  0.9630098339827987
R2:  0.9707201560468381

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.181e+06, tolerance: 3.009e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.698e+06, tolerance: 3.060e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.789e+06, tolerance: 4.039e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.115e+06, tolerance: 3.397e+04
  model = cd_fast.enet_coordinate_descent(

In [8]:
definitive_groups[0]

,ID_LOTE,DIAS_EN_EMERGER,DIAS_EN_EMERGER_A_FLORECER,DIAS_EN_FLORECER_A_COSECHAR,POBLACION_20DIAS_AJT,ALTURA_LOT,ContEnfQui_Emer_Flor,ContEnfQui_Flor_Cose,ContMalMec_Siem_Emer,ContMalMec_Emer_Flor,...,CAP_ENDURE_RASTA,MOTEADOS_RASTA,MOTEADOS_MAS70cm._RASTA,OBSERVA_EROSION_RASTA,OBSERVA_MOHO_RASTA,OBSERVA_RAICES_VIVAS_RASTA,OBSERVA_HOJARASCA_MO_RASTA,SUELO_NEGRO_BLANDO_RASTA,CUCHILLO_PRIMER_HTE_RASTA,CERCA_RIOS_QUEBRADAS_RASTA
1,4222,6,48,79,70000,17,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
2,4254,5,49,81,59700,18,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,3643,5,46,84,65000,9,0,0,0,0,...,0,1,0,0,0,1,0,0,1,1
4,3947,4,49,90,60000,7,1,0,0,0,...,0,0,0,0,0,1,0,0,1,1
5,2275,6,47,84,55000,8,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,2488,5,45,81,72000,10,0,0,0,0,...,1,0,0,0,0,1,1,0,1,1
158,2900,4,47,80,62000,9,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
159,2693,6,53,84,60000,10,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
160,3937,5,47,90,65000,6,0,0,0,0,...,1,1,0,0,0,1,0,0,0,1
161,2611,6,44,81,58000,18,1,0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [9]:
print("Grupos Definitivos: ", len(definitive_groups))

# Modelos Finales
list_final_models = []
for i in range(len(definitive_groups)):
    model_final, r2_final, yhat_final = LinearRegession(definitive_groups[i],0.1, 0.97).CalcularModeloLR()
    print("R2: ", r2_final)
    list_final_models.append(model_final)
    

grupos_finales = definitive_groups.copy()

Grupos Definitivos:  4
R2:  0.9725819476985545
R2:  0.9747155427618888
R2:  0.9630098339827987

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.181e+06, tolerance: 3.009e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.698e+06, tolerance: 3.060e+04
  model = cd_fast.enet_coordinate_descent(
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.789e+06, tolerance: 4.039e+04
  model = cd_fast.enet_coordinate_descent(

R2:  0.9707201560468381

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.115e+06, tolerance: 3.397e+04
  model = cd_fast.enet_coordinate_descent(

In [21]:
# Construimos datset de Trainign para etapa de clasificación
# ============================================================
final_datset_join = BuildGroupsQuality(grupos_finales)
print(final_datset_join.shape)

(719, 176)

In [7]:
dataset_ditancia = final_datset_join.drop(["RDT_AJUSTADO"], axis=1)
dataset_ditancia

,DIAS_EN_EMERGER,DIAS_EN_EMERGER_A_FLORECER,DIAS_EN_FLORECER_A_COSECHAR,POBLACION_20DIAS_AJT,ALTURA_LOT,ContEnfQui_Emer_Flor,ContEnfQui_Flor_Cose,ContMalMec_Siem_Emer,ContMalMec_Emer_Flor,ContMalMec_Flor_Cose,...,MOTEADOS_RASTA,MOTEADOS_MAS70cm._RASTA,OBSERVA_EROSION_RASTA,OBSERVA_MOHO_RASTA,OBSERVA_RAICES_VIVAS_RASTA,OBSERVA_HOJARASCA_MO_RASTA,SUELO_NEGRO_BLANDO_RASTA,CUCHILLO_PRIMER_HTE_RASTA,CERCA_RIOS_QUEBRADAS_RASTA,Grupo
0,6,48,79,70000,17,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,5,49,81,59700,18,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,5,46,84,65000,9,0,0,0,0,0,...,1,0,0,0,1,0,0,1,1,0
3,4,49,90,60000,7,1,0,0,0,0,...,0,0,0,0,1,0,0,1,1,0
4,6,47,84,55000,8,0,0,0,0,0,...,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,4,47,85,55000,11,0,0,0,0,0,...,1,0,0,0,1,0,0,1,0,3
715,5,51,83,59800,16,0,0,0,0,0,...,0,0,0,0,1,1,0,1,0,3
716,4,47,87,55000,4,0,0,0,0,0,...,1,0,0,0,1,0,0,1,0,3
717,6,49,84,65750,17,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,3
718,4,48,81,65000,6,0,0,0,0,0,...,1,0,0,0,0,0,0,1,1,3

In [8]:
# Agrgamos los limites para las predicciones reales
df_limite = final_datset_join.copy()
df_limite["RDT_mas15"] = df_limite.RDT_AJUSTADO*0.15 + df_limite.RDT_AJUSTADO
df_limite["RDT_menos15"] = df_limite.RDT_AJUSTADO - df_limite.RDT_AJUSTADO*0.15

In [10]:
limites_15 = df_limite[["RDT_AJUSTADO","RDT_mas15","RDT_menos15"]]
limites_15

     RDT_AJUSTADO  RDT_mas15  RDT_menos15
0         7303.72  8399.2780    6208.1620
1         6169.19  7094.5685    5243.8115
2         4767.44  5482.5560    4052.3240
3         6674.42  7675.5830    5673.2570
4         2383.72  2741.2780    2026.1620
..            ...        ...          ...
714       5053.49  5811.5135    4295.4665
715       6105.33  7021.1295    5189.5305
716       1158.14  1331.8610     984.4190
717       6310.47  7257.0405    5363.8995
718       5720.93  6579.0695    4862.7905

[719 rows x 3 columns]

In [39]:
df_norm = NormalizeViewMinable(dataset_ditancia.values[:,:-1],valMin, dataRange)
print(df_norm.shape)

(719, 174)

In [49]:
# df: Datasaset distancia que incluye los atributos con los grupos
def qualityFunction(df_norm, wi,df, lista_modelos, limites_15):
    #print("longitud df_norm: ",len(df_norm))
    #print("Longitud wi: ", len(wi))
    y_predicho = []
    contador = 0
    for i in range(len(df_norm)):
        vrf = df_norm[i] 
        minDep = sys.float_info.max
        posMinDep = 0
        for j in range(len(df_norm)):
            if i != j:
                ri = wi* np.power((df_norm[j] - vrf), 2)
                dE = np.sum(ri)
                if dE < minDep:
                    posMinDep=j
                    minDep = dE
        #print(posMinDep)
        modelo = df.values[posMinDep][-1]
        #print("Modelo: ", int(modelo))
        # caculamos la predicción de c/d registro con el modelo seleccionado
        y_pred = lista_modelos[int(modelo)].predict(df.values[:,:-1][i].reshape(1,-1))[0]
        #y_predicho.append(y_pred)
        
        
        if (y_pred >= limites_15.values[i][2]) & (y_pred <= limites_15.values[i][1]):
            contador = contador + 1
            #print("Entra")
        
    qs = contador/len(df_norm)
    #print("La Calidad es:  ", qs)
    return qs




def ImprovisationGBHS(PAR, hmn, nc,dataset_normalizado , lmp, HMRC,df,lista_modelos, limites_15):

    df_norm = dataset_normalizado

    # Se genera la memoria Armonica - diferentes tamaños
    np.random.seed(123)
    MA = GenerateArmonyMemory(df_norm,hmn,dataset_ditancia,lista_modelos, limites_15)
    P=len(MA[0]) 
    
    
    curvaFitnes = []
    vectorIteration= []
    for i in range (lmp):
        pesosAleatorios = np.random.rand(P-1)
        for j in range(P-1):
            Aleatorio1 = random.random() 
            if (Aleatorio1 < HMRC):
                pma = random.randint(0, hmn-1)
                pesosAleatorios[j]= MA[pma][j]

                Aleatorio2 = random.random()
                if Aleatorio2 < PAR:
                    pesosAleatorios[j] = MA[0][j]
            
            else:
                Aleatorio3 = random.random()
                if Aleatorio3 < nc/P:
                    Aleatorio4 = 0
                else:
                    Aleatorio4 = Aleatorio3/(P-nc)
                
                pesosAleatorios[j] = Aleatorio4
        
        
        print("Suma pesos aleatorios: ", pesosAleatorios.sum())
        # Normalización de los pesos
        sum = pesosAleatorios.sum()
        WN = pesosAleatorios / sum

        fitnes = qualityFunction(df_norm, WN,df,lista_modelos, limites_15)
        print("Funcion de calidad: ", fitnes)



        # Remplazo
        if MA[hmn -1][P-1] < fitnes:
            new_register = np.append(WN, fitnes)
            MA[hmn-1] = new_register
            #print("------------------------------------")
            MA.sort(key=lambda x: x[-1], reverse=True)
        

        
        curvaFitnes.append(MA[0][P-1])
        vectorIteration.append(MA[0])
        

    
    
    print("Valor de la curva en la ultima poisción: ",curvaFitnes[-1])
    '''
    dicc = {"vector":vectorIteration,
                "Fitnes": curvaFitnes}
    

    df_new = pd.DataFrame(data=dicc)
    df_new.to_csv(f"ResultadosImprovisacion/GBHS.csv")
    dicc = dict()
    '''
    return [curvaFitnes[-1], vectorIteration[-1]]

In [41]:
#
#  Prueba del vector de pesos y la funcion de calidad

wi = GenerateWeightVector(174)
Qs = qualityFunction(df_norm, wi,dataset_ditancia, list_final_models,  limites_15)

print("Calidad: ", Qs)

Calidad:  0.545201668984701

In [42]:
MA = GenerateArmonyMemory(df_norm,10,dataset_ditancia,list_final_models, limites_15)

In [43]:
MA

[array([6.25152975e-03, 9.03109658e-03, 8.69977562e-03, 3.01461489e-03,
        7.22760525e-03, 9.58458244e-03, 6.68598503e-03, 2.80924476e-03,
        6.77357824e-03, 8.85040837e-03, 2.50309501e-03, 1.66585732e-03,
        3.37102042e-03, 5.08146831e-03, 4.82830973e-03, 1.65344518e-03,
        9.82226822e-03, 5.70766342e-03, 7.41529352e-03, 6.30299795e-04,
        6.03040036e-03, 7.71888377e-03, 1.54174240e-03, 1.02828798e-02,
        9.26099125e-03, 4.33816970e-03, 7.46546671e-04, 5.15816844e-03,
        9.87684123e-03, 9.19517283e-03, 8.54181760e-03, 6.93721648e-03,
        8.45761375e-03, 9.77097382e-03, 6.04600339e-03, 2.75945305e-03,
        8.46540433e-03, 2.74659651e-03, 7.29573078e-04, 3.82005103e-03,
        9.98998196e-03, 1.53811750e-03, 3.10004217e-03, 3.43282893e-03,
        3.28277586e-03, 2.59018791e-03, 4.09691827e-03, 1.00612259e-02,
        8.94336873e-03, 2.25175237e-04, 1.02003780e-02, 4.29018682e-03,
        3.55409627e-03, 3.76960821e-03, 6.86216052e-03, 9.34216559e-03,
        1.06291904e-02, 7.14390573e-03, 1.09226259e-02, 5.30406915e-03,
        9.65976187e-03, 9.64513725e-03, 7.16760889e-03, 9.96509653e-03,
        4.38470522e-03, 2.56889125e-03, 7.17448154e-04, 5.68494705e-03,
        5.75139051e-03, 7.73131554e-03, 8.72573782e-03, 2.97134461e-03,
        1.07569174e-02, 4.64947666e-03, 4.14609311e-03, 1.67135027e-03,
        3.00304520e-03, 1.21141865e-03, 7.76277717e-03, 6.98136062e-03,
        1.06231583e-02, 7.09429849e-03, 5.15624334e-03, 1.62369691e-03,
        4.50959847e-03, 3.97492317e-03, 1.09444877e-02, 7.44508475e-03,
        6.54414003e-03, 8.60229309e-03, 4.59216303e-03, 5.01577810e-03,
        3.62308800e-03, 6.70644779e-03, 8.76623630e-03, 8.16035882e-03,
        3.09537410e-03, 4.02273911e-03, 2.62203814e-03, 3.24341247e-03,
        9.04932850e-04, 3.74822741e-03, 5.32087047e-03, 6.51543440e-03,
        1.65325722e-04, 3.88606888e-03, 6.29965462e-04, 4.76294066e-03,
        4.01562229e-03, 6.13954764e-03, 4.96365465e-03, 5.48037200e-03,
        4.89937289e-03, 6.07321527e-03, 8.91151795e-03, 8.66488253e-03,
        9.98273998e-03, 1.00362282e-02, 2.71911296e-03, 4.42228448e-03,
        8.78007870e-03, 7.04269987e-03, 2.64997703e-03, 4.85055594e-03,
        4.20654648e-03, 1.99995961e-03, 4.51307952e-03, 5.19780889e-03,
        4.66567559e-03, 5.40819546e-03, 4.95011466e-03, 2.34025378e-04,
        3.43312538e-04, 1.01534145e-02, 2.55688201e-04, 2.18450244e-03,
        1.06697571e-02, 2.15136718e-03, 9.95044860e-03, 4.92453094e-03,
        4.37192502e-03, 8.90636953e-03, 5.03120392e-03, 9.65590387e-03,
        8.39074193e-03, 1.00684699e-02, 5.24151433e-03, 4.07183427e-03,
        8.15356863e-03, 6.83798339e-04, 1.10067523e-02, 9.86026522e-03,
        7.47499175e-03, 8.97052033e-03, 6.41351496e-03, 6.46831841e-03,
        5.77288741e-03, 9.88101691e-03, 2.87513715e-03, 4.18890721e-03,
        5.80440671e-03, 1.91067456e-03, 8.68015278e-03, 1.12604796e-03,
        5.27928564e-03, 9.09931236e-03, 6.22385788e-03, 8.26422091e-03,
        9.25373280e-03, 6.20063455e-03, 2.77234601e-04, 9.21200563e-03,
        6.60930756e-03, 2.36539498e-03, 5.89707928e-01]),
 array([9.31431428e-03, 8.64593961e-03, 6.93795532e-04, 8.43663368e-04,
        4.13699191e-03, 4.20872268e-03, 1.11440263e-03, 1.18981891e-03,
        4.27544515e-03, 6.83924502e-03, 5.77313469e-03, 5.30129915e-04,
        3.81708176e-04, 3.69908357e-03, 9.86373936e-04, 1.50407630e-03,
        9.50313470e-03, 1.09503178e-02, 8.57814841e-03, 5.58170552e-03,
        4.49514993e-03, 9.71574177e-03, 1.14540768e-02, 6.88845163e-03,
        1.09906402e-02, 5.80456970e-03, 9.40653098e-04, 9.22947871e-03,
        1.08214171e-02, 1.06642411e-02, 7.43176640e-03, 1.65326363e-03,
        1.43642768e-03, 8.36688347e-03, 1.42099831e-03, 8.55007477e-03,
        4.01491836e-03, 4.95853390e-03, 1.43290895e-03, 6.00696611e-03,
        6.20103341e-03, 9.50134338e-03, 6.60043223e-03, 8.03296321e-03,
        5.94111802e-03, 1.13281330e-02, 7.28244745e-03, 8.14597660e-03,
        4.93427398e-03, 9.88272707e-03, 9.39315417e-03, 4.25541177e-03,
        1.03500109e-02, 6.58034503e-03, 6.68987177e-03, 8.96092048e-03,
        7.57927813e-03, 3.31092259e-03, 7.77892259e-03, 1.04556352e-02,
        4.45429819e-03, 4.72586814e-04, 1.00549955e-03, 8.34007877e-03,
        8.02414614e-03, 6.32672173e-03, 1.63268175e-03, 8.63619791e-03,
        5.88289561e-03, 1.06563694e-02, 1.05386710e-02, 1.33432382e-03,
        2.39042732e-03, 4.62710928e-03, 7.10569491e-03, 8.70741944e-03,
        3.28474182e-03, 1.14355021e-02, 4.21843147e-03, 6.81887126e-03,
        8.22047475e-03, 9.92931244e-03, 8.35578313e-03, 2.86918592e-03,
        1.64129350e-03, 7.39124308e-03, 8.85430309e-03, 2.25841838e-03,
        1.80162475e-03, 7.24631702e-03, 8.95001164e-03, 1.83778407e-03,
        7.60712888e-03, 3.47906202e-03, 2.11926020e-03, 7.31175903e-03,
        2.85752745e-03, 3.16868287e-03, 3.99958345e-03, 7.12844407e-05,
        2.46627714e-03, 9.92767301e-03, 2.79828102e-03, 6.97111365e-03,
        9.79822424e-03, 9.33258119e-03, 1.12450883e-02, 5.30195102e-03,
        4.21597940e-03, 1.12972838e-02, 8.39598219e-03, 6.34538446e-03,
        3.18028314e-03, 9.04521023e-03, 2.75990232e-03, 1.03341001e-02,
        2.32512348e-03, 4.44715641e-03, 2.77129215e-03, 7.88637952e-03,
        3.12739872e-03, 8.86561224e-04, 6.84061610e-03, 1.19661921e-03,
        5.22024976e-03, 3.69707919e-03, 1.03027743e-02, 2.05043265e-03,
        2.27131474e-03, 5.60105372e-03, 1.82005922e-04, 2.82602292e-03,
        2.55594350e-03, 8.98907173e-03, 9.13452093e-03, 1.09706776e-02,
        9.58644434e-03, 2.31524069e-03, 4.30990657e-03, 8.88363290e-03,
        4.64926157e-03, 9.28985290e-03, 1.66024129e-03, 7.49544297e-03,
        5.84441499e-03, 5.22702003e-03, 5.87414872e-03, 3.25985237e-04,
        1.57057337e-03, 6.49026711e-03, 5.12238052e-03, 5.19116800e-03,
        6.41936665e-03, 2.98518030e-03, 6.77926040e-03, 7.76109071e-03,
        6.08965845e-03, 5.92716519e-03, 7.48882997e-03, 6.67280499e-03,
        1.09440857e-02, 4.03694689e-03, 1.02833871e-02, 3.74009326e-03,
        2.94065865e-03, 8.42766049e-03, 8.90505938e-03, 4.32151223e-03,
        4.49593896e-04, 6.93243112e-03, 1.37676805e-03, 3.69033328e-03,
        6.32866614e-04, 8.56671343e-03, 5.74408901e-01]),
 array([9.47214766e-03, 9.01445074e-03, 2.61346392e-03, 1.34700772e-03,
        1.02878821e-02, 1.00717073e-02, 8.50198330e-05, 4.85083494e-03,
        7.46657030e-04, 9.81868670e-03, 9.25621682e-03, 6.36887698e-03,
        9.81749690e-03, 1.06084675e-02, 5.58806417e-03, 1.18978823e-03,
        5.61094872e-03, 7.06991440e-03, 1.14030094e-03, 8.91998335e-03,
        7.09740102e-03, 1.01501197e-02, 5.31728197e-03, 9.35634159e-04,
        3.27788817e-03, 1.06167667e-02, 5.34840743e-03, 9.52907574e-04,
        8.84856049e-05, 5.04496377e-03, 6.74133851e-03, 1.94982549e-03,
        1.03172077e-02, 1.00382648e-02, 2.15559916e-03, 8.98586134e-03,
        9.20118119e-03, 5.26185309e-03, 1.12524328e-02, 3.67945130e-03,
        3.52366526e-03, 6.69018841e-03, 9.43961391e-03, 6.30287565e-03,
        9.90915350e-03, 8.27759853e-03, 4.65315587e-03, 2.48343440e-03,
        9.37814360e-04, 8.91249550e-03, 4.05384417e-04, 6.20814166e-03,
        4.56148588e-03, 6.43766820e-03, 1.00206105e-02, 6.45447819e-03,
        5.49637245e-03, 2.15309536e-03, 4.68217947e-04, 1.05174290e-02,
        6.30678839e-03, 3.46408562e-03, 5.42687836e-03, 1.00833733e-02,
        6.00063132e-03, 9.60484503e-03, 2.39885069e-03, 1.12023035e-02,
        5.48221074e-03, 1.22232053e-03, 6.33398282e-03, 1.11392996e-02,
        8.82765172e-03, 2.10524358e-04, 8.90884661e-03, 7.40269647e-03,
        4.96641543e-03, 7.11787195e-03, 1.04485459e-03, 2.63223158e-03,
        4.33612962e-03, 5.70939879e-03, 3.59259439e-04, 1.11483989e-02,
        9.47156471e-03, 6.84986575e-03, 1.08798570e-02, 7.44345535e-04,
        8.11924230e-03, 1.11109698e-03, 1.04805409e-02, 8.41998874e-03,
        2.70050469e-03, 5.09407197e-03, 6.86163599e-03, 3.71441405e-03,
        7.97401339e-03, 9.64814408e-03, 2.87753018e-03, 7.35210615e-03,
        7.27773347e-03, 5.86190105e-03, 8.46134945e-03, 1.04243597e-02,
        2.03805991e-03, 1.41662349e-03, 6.09996820e-03, 9.64149906e-04,
        2.97492375e-03, 2.12867702e-03, 7.59802483e-03, 7.95441411e-03,
        4.14816323e-03, 2.34314270e-03, 7.09507385e-05, 5.07790946e-03,
        2.16933069e-03, 9.49020424e-03, 9.72819479e-03, 6.37121438e-03,
        2.68681849e-03, 3.18113735e-03, 9.14093857e-03, 5.40864400e-03,
        6.07286691e-03, 6.88257294e-03, 1.01916011e-02, 3.13467638e-03,
        4.16178930e-03, 9.69491190e-03, 2.06851754e-03, 1.45429448e-03,
        1.29655074e-03, 1.03975983e-02, 6.72405209e-03, 4.67795998e-03,
        1.84866131e-03, 1.04175717e-02, 5.42537884e-03, 2.66512499e-03,
        1.06100099e-02, 1.07481087e-03, 1.37368394e-03, 8.78025740e-03,
        4.90305841e-03, 3.61135933e-03, 9.50552516e-05, 7.10923503e-03,
        4.25715719e-03, 6.89774593e-03, 8.19363287e-03, 9.25895815e-03,
        6.28747410e-03, 3.33804695e-03, 9.06647874e-03, 2.90349191e-03,
        9.20543661e-04, 4.31871641e-03, 7.29806278e-03, 5.86064308e-03,
        3.50899954e-03, 9.60014970e-03, 3.05615554e-03, 3.34307828e-03,
        3.93952129e-03, 5.03675471e-03, 1.02002793e-02, 8.42479159e-03,
        6.42272910e-03, 1.10084850e-02, 3.76462844e-03, 1.01446332e-02,
        3.47245682e-03, 2.01551560e-03, 5.73018081e-01]),
 array([1.12940179e-03, 7.91668601e-03, 8.78662841e-03, 6.83083562e-03,
        4.01792204e-04, 8.17703856e-03, 2.19054688e-03, 3.12989872e-03,
        1.04919552e-02, 9.26419003e-03, 8.20522895e-03, 5.04140691e-03,
        8.25345420e-03, 1.05020359e-02, 6.13643078e-03, 1.05345548e-02,
        1.03958658e-02, 5.56615931e-03, 1.11767453e-02, 8.33340527e-03,
        1.47948768e-03, 2.73539278e-03, 5.19815082e-03, 6.92675562e-03,
        6.10825594e-03, 8.34913304e-03, 4.21887751e-03, 1.14286921e-02,
        9.24582973e-03, 4.21012283e-03, 2.88531621e-03, 1.11854318e-02,
        1.55120636e-03, 7.82688910e-03, 1.08363572e-02, 2.23685544e-03,
        9.60036491e-03, 9.87654998e-03, 9.04955415e-03, 1.43825063e-03,
        6.88415949e-03, 4.41156509e-03, 9.16373407e-03, 5.20079183e-03,
        2.17319023e-04, 2.80026957e-03, 5.71998716e-03, 6.44412569e-03,
        6.26589162e-03, 4.92033503e-03, 5.27840137e-04, 6.58386597e-03,
        6.34565310e-03, 8.85439127e-03, 9.80891752e-03, 2.90694933e-03,
        9.64088882e-04, 3.36974540e-03, 7.63799741e-03, 2.85400584e-03,
        9.09694962e-03, 6.16244481e-05, 1.19639421e-04, 6.07063633e-03,
        1.28837323e-04, 2.63035808e-03, 5.14065676e-03, 1.12379060e-02,
        7.60353479e-03, 1.08085379e-02, 9.56868515e-03, 6.58831191e-03,
        3.40956343e-04, 6.21092016e-03, 7.89661953e-03, 8.54408022e-03,
        5.77949825e-03, 5.37345296e-03, 4.54081630e-03, 4.11890315e-03,
        6.28429800e-03, 9.93612146e-03, 6.92627701e-03, 1.07940194e-02,
        1.14327513e-02, 1.01851385e-02, 6.31272483e-03, 3.92052196e-03,
        2.63897941e-03, 1.00992272e-03, 9.64750226e-03, 6.21305428e-03,
        2.21630503e-04, 7.15465839e-05, 9.88420505e-03, 7.21191049e-04,
        6.98498218e-03, 8.39129521e-04, 1.86394000e-03, 6.94399884e-03,
        5.34477417e-03, 9.35266535e-03, 6.03196751e-03, 2.98583721e-04,
        1.14362106e-02, 4.43705039e-03, 8.35399585e-03, 8.36749489e-05,
        1.05125432e-02, 2.43719897e-03, 1.52108058e-03, 2.13371933e-03,
        4.48194675e-03, 1.19397935e-03, 4.89710165e-03, 8.64453754e-03,
        8.04421782e-03, 7.67308379e-03, 9.01202418e-03, 3.24822858e-03,
        1.22869115e-03, 6.56034963e-03, 6.35416688e-03, 1.13731142e-02,
        8.92591900e-03, 7.51633864e-03, 1.39895280e-04, 1.05001993e-03,
        7.84923736e-04, 5.17174585e-03, 8.65892879e-03, 1.02417876e-03,
        6.83331029e-03, 1.07784856e-02, 7.53270134e-03, 1.08997639e-02,
        6.52616533e-03, 4.44746743e-04, 1.11841504e-02, 5.75210477e-03,
        3.10808269e-03, 8.33028057e-03, 5.37873602e-03, 4.04570178e-03,
        2.70025176e-03, 1.67665799e-03, 3.80467404e-03, 8.93698601e-03,
        1.10757346e-02, 8.12398929e-03, 2.66175592e-03, 5.90772988e-03,
        6.69523691e-03, 3.92853973e-03, 1.12698017e-02, 6.63194693e-03,
        4.78962978e-03, 1.01710224e-03, 6.39948932e-03, 5.57622371e-03,
        2.05321037e-03, 7.82874179e-03, 2.85960091e-03, 2.28662044e-03,
        5.53797013e-03, 6.58039004e-03, 4.77753847e-03, 3.99059965e-03,
        9.65329937e-03, 1.57279918e-04, 6.19938174e-03, 3.49029817e-03,
        6.44843716e-03, 2.77356898e-03, 5.73018081e-01]),
 array([8.72691235e-03, 9.62715599e-03, 8.36061925e-03, 9.87692067e-04,
        1.61462850e-03, 8.39034154e-03, 8.94231895e-03, 3.53919174e-03,
        5.67307107e-03, 7.88767517e-03, 8.27595904e-03, 3.84437330e-03,
        4.35719824e-03, 7.33047553e-04, 3.06962500e-03, 6.67531668e-03,
        5.53593272e-03, 7.21183110e-03, 5.57001245e-03, 2.43834297e-03,
        5.92560077e-03, 1.17273989e-02, 2.26817513e-03, 3.52282593e-03,
        5.52406005e-03, 3.10384379e-03, 5.20030778e-03, 6.12460973e-03,
        3.71746660e-04, 3.92049380e-03, 2.67531018e-03, 4.78267876e-03,
        1.15197183e-02, 2.15518178e-03, 2.26345155e-03, 9.58505934e-03,
        9.92129979e-03, 8.08819684e-03, 5.30229578e-03, 3.99583128e-03,
        1.01856081e-02, 4.69568788e-03, 3.29189817e-03, 1.03568867e-02,
        8.41638102e-03, 5.20717632e-04, 5.93459012e-03, 8.14219308e-03,
        1.00861669e-02, 1.00252233e-02, 6.22836309e-03, 9.43776201e-03,
        6.40141944e-03, 3.71658879e-03, 2.30529674e-03, 8.60895119e-03,
        1.13819722e-02, 5.46911057e-04, 5.02675146e-03, 5.42035818e-03,
        9.55096860e-03, 4.84927057e-03, 7.77127148e-03, 6.24354354e-03,
        4.84927686e-03, 7.04002676e-03, 8.86774019e-04, 1.68943009e-03,
        7.76509712e-03, 7.67796254e-03, 2.61241647e-03, 3.12356752e-03,
        2.29835878e-03, 5.32141890e-03, 2.38120174e-03, 7.40913639e-03,
        9.14079202e-03, 1.00038839e-02, 6.74951219e-03, 2.24555924e-03,
        3.72408640e-03, 1.05967659e-02, 6.96466008e-03, 2.65813965e-03,
        5.87815389e-03, 5.37056183e-03, 1.85470222e-03, 7.26791796e-03,
        6.16597982e-03, 9.32304239e-04, 1.14903794e-03, 3.15570986e-03,
        1.00510578e-02, 3.12311831e-03, 8.65479140e-03, 2.22629240e-03,
        2.79699100e-03, 1.61554472e-03, 4.79907231e-03, 7.96490320e-03,
        5.49748700e-04, 5.74166042e-03, 4.51110770e-03, 6.18831804e-03,
        7.85607750e-03, 1.05739489e-02, 2.18043716e-03, 6.93602262e-03,
        2.48104686e-03, 5.14444212e-03, 4.99546013e-04, 1.00281504e-02,
        1.28401180e-03, 7.57176510e-03, 6.25260836e-03, 9.56103036e-03,
        8.50169050e-03, 4.09222345e-03, 6.97028281e-03, 8.53612459e-03,
        6.74715463e-03, 2.64630166e-03, 8.83603664e-03, 1.07014567e-02,
        1.06553360e-02, 4.69603671e-03, 4.74657621e-03, 1.10717622e-02,
        7.84428894e-03, 4.19678132e-03, 3.55862620e-03, 1.04603348e-02,
        2.67171957e-03, 1.68500783e-03, 7.25440984e-03, 2.22313912e-03,
        2.18997883e-03, 1.66836760e-03, 8.03732781e-03, 2.90658272e-04,
        2.85496477e-03, 1.14190655e-02, 6.53881193e-03, 9.56664058e-03,
        7.65256307e-03, 4.99026916e-03, 5.93854073e-03, 9.04171694e-03,
        1.10447839e-02, 5.14124165e-04, 4.56842328e-03, 6.03010274e-03,
        9.48365788e-03, 1.59931803e-03, 1.47939099e-03, 2.97900923e-03,
        1.02626488e-02, 3.63607764e-03, 1.19778979e-02, 9.37643009e-03,
        1.67345961e-03, 9.09981406e-03, 4.80925139e-03, 1.87574280e-03,
        7.51831567e-03, 2.82963341e-03, 1.04288365e-02, 5.23157666e-03,
        1.10473295e-02, 5.12513502e-03, 6.82380553e-03, 8.54969221e-03,
        3.71256555e-03, 5.95054216e-03, 5.71627260e-01]),
 array([7.00632913e-03, 7.96263598e-04, 2.87380906e-03, 5.30571003e-04,
        9.24727919e-03, 6.83947795e-03, 9.99587211e-03, 8.17904657e-03,
        3.40954673e-03, 8.25257564e-03, 1.08845560e-02, 5.46977014e-03,
        6.35544722e-03, 8.08956031e-03, 5.81819967e-05, 3.51592218e-03,
        9.40795962e-03, 2.67750365e-03, 8.98027222e-03, 5.34230476e-03,
        2.59903135e-04, 8.48184281e-04, 1.01675322e-02, 4.60050836e-03,
        4.81944009e-03, 1.04783855e-02, 7.65427199e-03, 4.70940471e-03,
        8.84492903e-03, 9.79482049e-03, 9.56608051e-03, 5.07053459e-03,
        1.01700962e-02, 8.35868587e-03, 7.89419301e-03, 2.45350217e-03,
        4.59387131e-03, 9.96804057e-03, 2.19646619e-03, 9.27933787e-03,
        3.74261588e-03, 5.04260511e-03, 5.91905797e-03, 5.40795344e-03,
        6.31599397e-03, 3.52706808e-03, 4.41311894e-04, 3.69835537e-03,
        1.02398153e-02, 7.69909793e-03, 3.43566274e-03, 2.35473386e-03,
        4.30092175e-03, 1.39166433e-03, 5.17934658e-03, 5.81981514e-04,
        1.76930036e-03, 6.29622737e-03, 2.14271886e-03, 2.45047000e-04,
        1.05589212e-02, 3.87957015e-03, 3.42044929e-03, 9.77535356e-03,
        9.77635256e-03, 1.03369281e-02, 5.87266222e-03, 8.82197401e-03,
        1.07756381e-02, 4.23000110e-03, 8.83577835e-03, 1.21008910e-03,
        6.91028636e-03, 3.82557574e-03, 7.28966577e-03, 7.38540522e-03,
        5.20998326e-03, 5.70872814e-03, 5.32493207e-03, 8.96700660e-04,
        4.09784862e-03, 7.98936761e-03, 1.24094520e-03, 7.11560458e-04,
        6.99656592e-03, 8.17948964e-03, 4.78789845e-03, 2.14692852e-03,
        5.99907773e-03, 7.36670633e-03, 7.21138353e-03, 7.34106977e-03,
        5.79359300e-04, 3.85627330e-03, 7.17659690e-03, 6.95717485e-03,
        3.89815201e-03, 7.49628135e-03, 1.78553307e-03, 7.40200173e-03,
        1.05419354e-02, 7.15699556e-03, 4.49557583e-03, 1.27328791e-03,
        1.62148790e-03, 1.06216238e-02, 4.56536502e-03, 1.02853858e-02,
        4.30990071e-03, 1.43917724e-03, 4.73840807e-03, 5.36644218e-03,
        5.44413853e-03, 9.23789765e-03, 4.91929488e-03, 3.87693858e-03,
        9.29555203e-03, 1.07565543e-03, 8.44202059e-03, 5.78980971e-03,
        8.59833150e-03, 7.64776623e-03, 4.80424892e-03, 4.81837671e-03,
        7.40092452e-04, 4.66874999e-03, 1.03956663e-02, 5.27184844e-03,
        7.80113523e-03, 9.50029449e-03, 9.49384147e-03, 4.38507811e-03,
        1.06889458e-03, 1.00076720e-02, 1.10529430e-02, 1.07655867e-02,
        1.05153489e-02, 6.91443238e-03, 2.26215172e-03, 7.55920812e-03,
        1.13584490e-03, 4.62318554e-03, 5.96069606e-03, 9.78356379e-03,
        7.37359914e-03, 5.11609696e-03, 8.81915151e-03, 2.07144190e-03,
        4.78474110e-04, 1.53166585e-03, 5.78632559e-03, 5.03247181e-03,
        6.52909451e-03, 4.72920358e-03, 5.38655439e-03, 1.61167129e-03,
        2.57404215e-03, 6.21180052e-03, 1.53338208e-03, 1.04227242e-02,
        1.02509535e-02, 8.06248120e-03, 1.06689449e-02, 9.32749385e-03,
        7.30664694e-03, 4.40067193e-03, 4.20451085e-03, 2.20785866e-03,
        7.45468734e-03, 8.75740797e-03, 9.89727392e-03, 6.77743258e-04,
        3.48653206e-03, 1.18011800e-03, 5.71627260e-01]),
 array([7.22944496e-04, 3.28294899e-03, 3.76284057e-03, 4.07675258e-03,
        8.27789460e-03, 1.87329118e-03, 3.35426437e-04, 8.60616881e-03,
        1.46708025e-04, 1.73980755e-03, 2.58469064e-03, 9.60319593e-03,
        2.41461541e-03, 6.98185320e-03, 1.75721870e-03, 4.57496514e-03,
        4.12257654e-03, 1.37004060e-03, 1.40483344e-03, 9.36507996e-03,
        5.87427093e-03, 7.34352597e-03, 3.42508682e-03, 8.05543118e-03,
        3.01429780e-03, 3.54034947e-03, 1.06800262e-02, 1.10509149e-02,
        6.95077696e-03, 8.69085413e-03, 8.22029250e-03, 8.22265563e-03,
        3.62901232e-03, 7.12564702e-03, 5.81327798e-03, 2.34704072e-03,
        4.45546079e-03, 5.20154810e-03, 9.26895610e-03, 3.90596137e-03,
        5.27263365e-03, 6.49862605e-03, 7.88667842e-03, 1.03855689e-03,
        2.25791011e-03, 1.03429048e-02, 6.04972124e-04, 5.53434080e-03,
        2.76894043e-03, 1.07073668e-02, 1.12293340e-02, 1.05005188e-02,
        4.18541899e-04, 5.72973639e-03, 1.03318162e-02, 3.59598326e-03,

In [50]:
metric, vector_pesos =  ImprovisationGBHS(0.4, 20, 50, df_norm, 100, 0.85, dataset_ditancia,list_final_models, limites_15)

Suma pesos aleatorios:  0.904044258148516
Funcion de calidad:  0.5855354659248957
Suma pesos aleatorios:  1.0069929178045625
Funcion de calidad:  0.5952712100139083
Suma pesos aleatorios:  0.9524564811326522
Funcion de calidad:  0.5591098748261474
Suma pesos aleatorios:  0.936666913684646
Funcion de calidad:  0.5869262865090403
Suma pesos aleatorios:  0.8282107549313582
Funcion de calidad:  0.5841446453407511
Suma pesos aleatorios:  0.8556980772588425
Funcion de calidad:  0.5855354659248957
Suma pesos aleatorios:  0.925318955210275
Funcion de calidad:  0.5938803894297635
Suma pesos aleatorios:  0.9954947617613146
Funcion de calidad:  0.5841446453407511
Suma pesos aleatorios:  0.9487713928978982
Funcion de calidad:  0.5757997218358831
Suma pesos aleatorios:  0.947308894506762
Funcion de calidad:  0.5674547983310153
Suma pesos aleatorios:  0.9450604286555273
Funcion de calidad:  0.5813630041724618
Suma pesos aleatorios:  0.9714368441710792
Funcion de calidad:  0.56884561891516
Suma pesos aleatorios:  0.9633026562148781
Funcion de calidad:  0.5910987482614742
Suma pesos aleatorios:  0.9364098508012411
Funcion de calidad:  0.5980528511821975
Suma pesos aleatorios:  0.9626109471637322
Funcion de calidad:  0.5591098748261474
Suma pesos aleatorios:  0.9497167315793051
Funcion de calidad:  0.5702364394993046
Suma pesos aleatorios:  0.9258915510781041
Funcion de calidad:  0.5827538247566064
Suma pesos aleatorios:  0.9547091562423357
Funcion de calidad:  0.5632823365785814
Suma pesos aleatorios:  0.930904010534706
Funcion de calidad:  0.5924895688456189
Suma pesos aleatorios:  0.9194478572439648
Funcion de calidad:  0.5841446453407511
Suma pesos aleatorios:  0.9210767591671979
Funcion de calidad:  0.5785813630041725
Suma pesos aleatorios:  1.0464155030140898
Funcion de calidad:  0.5757997218358831
Suma pesos aleatorios:  0.9702605150703179
Funcion de calidad:  0.5994436717663422
Suma pesos aleatorios:  0.9414800257761563

:

In [19]:
sum(vector_pesos)

1.625869262865091