## IMPUTACION DE DATOS Y AGREGACIÓN DE DATOS DEL CLIMA.

-  Autor: Germán Homero Morán Figueroa
-  Descripción: En este notebook se realiza la imputación de datos faltantes en algunas columnas, con el obetivo de contruir una vista minable robusta para alimentar los modelos de machine Learning. Ademas se agrega información del clima para cada uno de los lotes especificados.
-  Salida: Vista Minable depurada , con información del clima lista para ser utilizada en los entreanmientos de algortimos de Machine Learning.

In [15]:
# Librerias y dependencias
# ================================================
import numpy as np
import pandas as pd
from statistics import median,mode

In [16]:
# Lectura del datframe (Contiene info de controles, fertilizaciín y suelo)
# =================================================================
matrizFinal = pd.read_csv("../../Data/Gold/datasetFinal_soil.csv")
matrizFinal.head(5)

,ID_EVENTO,ID_LOTE,TIPO_SIEMBRA,SEM_TRATADAS,MATERIAL_GENETICO,CULT_ANT,DRENAJE,METODO_COSECHA,ALMACENAMIENTO_FINCA,AREA,...,porc_FA,porc_AF,porc_BLANDO,porc_DURO,porc_EXT_DURO,porc_FRIABLE,porc_FIRME,porc_EXT_FIRME,porc_PLASTICO,porc_MUY_PLASTICO
0,53,40,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,1.0,...,61.73,0.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,54,43,Mecanizado,SI,DK 234,Maiz,SI,Manual,NO,1.0,...,0.00,0.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,56,44,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,1.0,...,0.00,48.72,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,57,45,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,1.0,...,0.00,0.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,273,46,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,1.0,...,0.00,0.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
#  Descripción de las columnas del dataset
# =================================================
matrizFinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 97 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID_EVENTO                           804 non-null    int64
 1   ID_LOTE                             804 non-null    int64
 2   TIPO_SIEMBRA                        803 non-null    object
 3   SEM_TRATADAS                        804 non-null    object
 4   MATERIAL_GENETICO                   803 non-null    object
 5   CULT_ANT                            800 non-null    object
 6   DRENAJE                             804 non-null    object
 7   METODO_COSECHA                      804 non-null    object
 8   ALMACENAMIENTO_FINCA                804 non-null    object
 9   AREA                                804 non-null    float64
 10  RDT_AJUSTADO                        804 non-null    float64
 11  DIAS_EN_EMERGER                     800 non-null    float64
 12  DIAS_EN_EMERGER_A_FLORECER          800 non-null    float64
 13  DIAS_EN_FLORECER_A_COSECHAR         800 non-null    float64
 14  POBLACION_20DIAS_AJT                804 non-null    object
 15  ALTURA_LOT                          804 non-null    int64
 16  ContEnfQui_Antes_Siem               804 non-null    int64
 17  ContEnfQui_Siem_Eme                 804 non-null    int64
 18  ContEnfQui_Emer_Flor                804 non-null    int64
 19  ContEnfQui_Flor_Cose                804 non-null    int64
 20  ContMalMec_Antes_Siem               804 non-null    int64
 21  ContMalMec_Siem_Emer                804 non-null    int64
 22  ContMalMec_Emer_Flor                804 non-null    int64
 23  ContMalMec_Flor_Cose                804 non-null    int64
 24  ContMalQui_Antes_Siem               804 non-null    int64
 25  ContMalQui_Siem_Emer                804 non-null    int64
 26  ContMalQui_Emer_Flor                804 non-null    int64
 27  ContMalQui_Flor_Cose                804 non-null    int64
 28  ContPlaQui_Antes_Siem               804 non-null    int64
 29  ContPlaQui_Siem_Emer                804 non-null    int64
 30  ContPlaQui_Emer_Flor                804 non-null    int64
 31  ContPlaQui_Flor_Cose                804 non-null    int64
 32  TotN_Antes_Siem                     804 non-null    float64
 33  TotN_Siem_Emer                      804 non-null    float64
 34  TotN_Emer_Flor                      804 non-null    float64
 35  TotP_Antes_Siem                     804 non-null    int64
 36  TotP_Siem_Emer                      804 non-null    float64
 37  TotP_Emer_Flor                      804 non-null    float64
 38  TotK_Antes_Siem                     804 non-null    int64
 39  TotK_Siem_Emer                      804 non-null    float64
 40  TotK_Emer_Flor                      804 non-null    float64
 41  FerOrg_Antes_Siem                   804 non-null    int64
 42  FerOrg_Siem_Emer                    804 non-null    int64
 43  FerOrg_Emer_Flor                    804 non-null    int64
 44  FerQui_Antes_Siem                   804 non-null    int64
 45  FerQui_Siem_Emer                    804 non-null    int64
 46  FerQui_Emer_Flor                    804 non-null    int64
 47  PENDIENTE_RASTA                     804 non-null    float64
 48  TERRENO_CIRCUN_RASTA                804 non-null    object
 49  POSICION_PERFIL_RASTA               804 non-null    object
 50  NO_CAPAS_RASTA                      804 non-null    float64
 51  PH_RASTA                            804 non-null    float64
 52  PEDREG_PERFIL_ROCAS                 804 non-null    object
 53  CAP_ENDURE_RASTA                    804 non-null    object
 54  PROFUND_CAP_ENDURE_RASTA            804 non-null    float64
 55  ESPESOR_CAP_ENDURE_RASTA            804 non-null    float64
 56  MOTEADOS_RASTA                      804 non-null    object
 57  PROFUND_MOTEADOS_RASTA              743 non-null    float64
 58  MOTEADOS_MAS70cm._RASTA             804 non-null    object
 59  ESTRUCTURA_RASTA                    804 non-null    object
 60  OBSERVA_EROSION_RASTA               804 non-null    object
 61  OBSERVA_MOHO_RASTA                  804 non-null    object
 62  OBSERVA_COSTRAS_DURAS_RASTA         804 non-null    object
 63  SITIO_EXPUESTO_SOL_RASTA            804 non-null    object
 64  OBSERVA_COSTRAS_BLANCAS_RASTA       804 non-null    object
 65  OBSERVA_COSTAS_NEGRAS_RASTA         804 non-null    object
 66  REGION_SECA_ARIDA_RASTA             804 non-null    object
 67  OBSERVA_RAICES_VIVAS_RASTA          804 non-null    object
 68  PROFUND_RAICES_VIVAS_RASTA          804 non-null    float64
 69  OBSERVA_PLANTAS_PEQUENAS_RASTA      804 non-null    object
 70  OBSERVA_HOJARASCA_MO_RASTA          804 non-null    object
 71  SUELO_NEGRO_BLANDO_RASTA            804 non-null    object
 72  CUCHILLO_PRIMER_HTE_RASTA           804 non-null    object
 73  CERCA_RIOS_QUEBRADAS_RASTA          804 non-null    object
 74  RECUBRIMIENTO_VEGETAL__SUELO_RASTA  804 non-null    object
 75  prof_efectiva                       804 non-null    float64
 76  d.interno                           804 non-null    object
 77  drenaje_externo                     804 non-null    object
 78  porc_A                              804 non-null    float64
 79  porc_Ar                             804 non-null    float64
 80  porc_ArA                            804 non-null    float64
 81  porc_ArL                            804 non-null    float64
 82  porc_FrL                            804 non-null    float64
 83  porc_L                              804 non-null    float64
 84  porc_F                              804 non-null    float64
 85  porc_ArF                            804 non-null    float64
 86  porc_FAr                            804 non-null    float64
 87  porc_FA                             804 non-null    float64
 88  porc_AF                             804 non-null    float64
 89  porc_BLANDO                         804 non-null    float64
 90  porc_DURO                           804 non-null    float64
 91  porc_EXT_DURO                       804 non-null    float64
 92  porc_FRIABLE                        804 non-null    float64
 93  porc_FIRME                          804 non-null    float64
 94  porc_EXT_FIRME                      804 non-null    float64
 95  porc_PLASTICO                       804 non-null    float64
 96  porc_MUY_PLASTICO                   804 non-null    float64
dtypes: float64(39), int64(27), object(31)
memory usage: 609.4+ KB

In [18]:
# conteo de la cantidad de nulos para c/u de las columnas
# ================================================================
matrizFinal.isnull().sum().sort_values(ascending=False).head(20)

PROFUND_MOTEADOS_RASTA            61
CULT_ANT                           4
DIAS_EN_FLORECER_A_COSECHAR        4
DIAS_EN_EMERGER_A_FLORECER         4
DIAS_EN_EMERGER                    4
TIPO_SIEMBRA                       1
MATERIAL_GENETICO                  1
PROFUND_RAICES_VIVAS_RASTA         0
REGION_SECA_ARIDA_RASTA            0
OBSERVA_RAICES_VIVAS_RASTA         0
ID_EVENTO                          0
OBSERVA_PLANTAS_PEQUENAS_RASTA     0
OBSERVA_COSTRAS_BLANCAS_RASTA      0
OBSERVA_HOJARASCA_MO_RASTA         0
SUELO_NEGRO_BLANDO_RASTA           0
CUCHILLO_PRIMER_HTE_RASTA          0
OBSERVA_COSTAS_NEGRAS_RASTA        0
OBSERVA_EROSION_RASTA              0
SITIO_EXPUESTO_SOL_RASTA           0
OBSERVA_COSTRAS_DURAS_RASTA        0
dtype: int64

*Nota*: En este caso como el porcentaje de valores nulos en la mayoria de columnas  es menor al 1% se decidio utilizar tecnicas estadisticas como: (moda , mediana, variznza ) para realizar dicha emputación de los datos faltantes.

In [19]:
# Para material Genetico
matrizFinal.MATERIAL_GENETICO.value_counts()

MATERIAL_GENETICO
Otro                   239
DK 234                 107
P3966 (Pioneer)         87
DK 234 YGRR             81
P4082 (Pioneer)         54
PIONEER 30F35 HRR       52
PAC 105                 41
DK7088                  32
ADV 9339 (Syngenta)     25
Impacto (Syngenta)      23
PIONEER 30F35           16
PIONEER 30F35 H         12
ADV 9293 (Syngenta)      8
PIONEER 30F32            5
Sinko (Syngenta)         3
DK 1596                  2
ICA V 156                2
FNC 114                  2
NK254 (Syngenta)         2
ICA V 109                2
Cerato (Syngenta)        2
DK 1040                  1
PIONEER 30F32HW          1
ICA V 305                1
CORPOICA V 114           1
FNC 3056                 1
Status (Syngenta)        1
Name: count, dtype: int64

In [20]:
# Se calcula (moda, media )  para c/d variable segun corresponda
# ========================================================

# Material Genetico
mode_MG = mode(matrizFinal.MATERIAL_GENETICO)
print("Moda Material Gnetico: ", mode_MG)

# Tipo Siembra
mode_TS = mode(matrizFinal.TIPO_SIEMBRA)
print("La moda para la variable TIPO_SIEMBRA: ",mode_TS)

# Dias Emerger
median_DEE = median(matrizFinal.DIAS_EN_EMERGER)
print("La media parala variable DIAS_EN_EMERGER es: ",median_DEE)

# Dias Emerger a Florecer
median_DEEF = median(matrizFinal.DIAS_EN_EMERGER_A_FLORECER)
print("La media parala variable DIAS_EN_EMERGER es: ",median_DEEF)

# Dias Florecer a Cosechar
median_DEFC = median(matrizFinal.DIAS_EN_FLORECER_A_COSECHAR)
print("La media parala variable DIAS_EN_FLORECER_A_COSECHAR es: ",median_DEFC)

# Cultivo Anterior
mode_CA = mode(matrizFinal.CULT_ANT)
print("La moda parala variable CULT_ANT es: ",mode_CA)

# Profundiad moteados rasta
median_PMR =median(matrizFinal.PROFUND_MOTEADOS_RASTA)
print("La media para al variable PROFUND_MOTEADOS_RASTA es: ", median_PMR)

Moda Material Gnetico:  Otro
La moda para la variable TIPO_SIEMBRA:  Mecanizado
La media parala variable DIAS_EN_EMERGER es:  5.0
La media parala variable DIAS_EN_EMERGER es:  53.0
La media parala variable DIAS_EN_FLORECER_A_COSECHAR es:  72.0
La moda parala variable CULT_ANT es:  Algodón
La media para al variable PROFUND_MOTEADOS_RASTA es:  -1.0

In [21]:
# Rempleazo de c/u de los valores faltantes en cada columna
# ===================================================================================================
matrizFinal.MATERIAL_GENETICO[matrizFinal.MATERIAL_GENETICO.isnull()] = mode_MG
matrizFinal.TIPO_SIEMBRA[matrizFinal.TIPO_SIEMBRA.isnull()] = mode_TS
matrizFinal.DIAS_EN_EMERGER[matrizFinal.DIAS_EN_EMERGER.isnull()] = median_DEE
matrizFinal.DIAS_EN_EMERGER_A_FLORECER[matrizFinal.DIAS_EN_EMERGER_A_FLORECER.isnull()] = median_DEEF
matrizFinal.DIAS_EN_FLORECER_A_COSECHAR[matrizFinal.DIAS_EN_FLORECER_A_COSECHAR.isnull()] = median_DEFC
matrizFinal.CULT_ANT[matrizFinal.CULT_ANT.isnull()] = mode_CA
matrizFinal.PROFUND_MOTEADOS_RASTA[matrizFinal.PROFUND_MOTEADOS_RASTA.isnull()]= median_PMR

C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.MATERIAL_GENETICO[matrizFinal.MATERIAL_GENETICO.isnull()] = mode_MG
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.MATERIAL_GENETICO[matrizFinal.MATERIAL_GENETICO.isnull()] = mode_MG
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.TIPO_SIEMBRA[matrizFinal.TIPO_SIEMBRA.isnull()] = mode_TS
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.TIPO_SIEMBRA[matrizFinal.TIPO_SIEMBRA.isnull()] = mode_TS
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.DIAS_EN_EMERGER[matrizFinal.DIAS_EN_EMERGER.isnull()] = median_DEE
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.DIAS_EN_EMERGER[matrizFinal.DIAS_EN_EMERGER.isnull()] = median_DEE
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.DIAS_EN_EMERGER_A_FLORECER[matrizFinal.DIAS_EN_EMERGER_A_FLORECER.isnull()] = median_DEEF
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.DIAS_EN_EMERGER_A_FLORECER[matrizFinal.DIAS_EN_EMERGER_A_FLORECER.isnull()] = median_DEEF
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.DIAS_EN_FLORECER_A_COSECHAR[matrizFinal.DIAS_EN_FLORECER_A_COSECHAR.isnull()] = median_DEFC
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.DIAS_EN_FLORECER_A_COSECHAR[matrizFinal.DIAS_EN_FLORECER_A_COSECHAR.isnull()] = median_DEFC
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.CULT_ANT[matrizFinal.CULT_ANT.isnull()] = mode_CA
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.CULT_ANT[matrizFinal.CULT_ANT.isnull()] = mode_CA
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matrizFinal.PROFUND_MOTEADOS_RASTA[matrizFinal.PROFUND_MOTEADOS_RASTA.isnull()]= median_PMR
C:\Users\germanm\AppData\Local\Temp\ipykernel_22004\3290917339.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrizFinal.PROFUND_MOTEADOS_RASTA[matrizFinal.PROFUND_MOTEADOS_RASTA.isnull()]= median_PMR

In [22]:
# Verificación de la imputación de datos
# ================================================================
matrizFinal.isnull().sum().sort_values(ascending=True).head(20)

ID_EVENTO                         0
OBSERVA_PLANTAS_PEQUENAS_RASTA    0
PROFUND_RAICES_VIVAS_RASTA        0
OBSERVA_RAICES_VIVAS_RASTA        0
REGION_SECA_ARIDA_RASTA           0
OBSERVA_COSTAS_NEGRAS_RASTA       0
OBSERVA_COSTRAS_BLANCAS_RASTA     0
SITIO_EXPUESTO_SOL_RASTA          0
OBSERVA_COSTRAS_DURAS_RASTA       0
OBSERVA_MOHO_RASTA                0
OBSERVA_HOJARASCA_MO_RASTA        0
OBSERVA_EROSION_RASTA             0
MOTEADOS_MAS70cm._RASTA           0
PROFUND_MOTEADOS_RASTA            0
MOTEADOS_RASTA                    0
ESPESOR_CAP_ENDURE_RASTA          0
PROFUND_CAP_ENDURE_RASTA          0
CAP_ENDURE_RASTA                  0
PEDREG_PERFIL_ROCAS               0
PH_RASTA                          0
dtype: int64

## 1. Tratamiento para el CLIMA

Se agrean datos del clima para los lotes con ID_LOTES especificos. Esta Iformación fue proporcionada por el IDEAM.

In [23]:
# Lectura de los datos.
# ===============================================================
df_clima = pd.read_csv("../../Data/Externas/Weather_events.csv")
df_clima.head(5)

,ID_EVENTO,Temp_Max_Avg_Veg,Temp_Min_Avg_Veg,Temp_Avg_Veg,Diurnal_Range_Avg_Veg,Sol_Ener_Accu_Veg,Temp_Max_34_Freq_Veg,Rain_Accu_Veg,Rain_10_Freq_Veg,Temp_Min_15_Freq_Veg,...,Temp_Max_Avg_Mad,Temp_Min_Avg_Mad,Temp_Avg_Mad,Diurnal_Range_Avg_Mad,Sol_Ener_Accu_Mad,Temp_Max_34_Freq_Mad,Rain_Accu_Mad,Rain_10_Freq_Mad,Temp_Min_15_Freq_Mad,Rhum_Avg_Mad
0,53,32.480345,24.3625,28.421423,8.117845,14804.75763,0.15,164.7,0.075,0,...,32.047671,23.602564,27.825117,8.445107,13197.57290,0.051282,279.3,0.230769,0,82.410256
1,54,32.052444,24.2525,28.152472,7.799944,14546.30944,0.10,248.6,0.125,0,...,32.372137,23.485714,27.928926,8.886423,12436.48772,0.028571,221.2,0.257143,0,81.857143
2,56,32.519587,24.3575,28.438543,8.162087,14905.91953,0.15,164.7,0.075,0,...,32.167009,23.533333,27.850171,8.633676,11267.16834,0.030303,226.0,0.272727,0,82.606061
3,57,32.322705,24.2800,28.301352,8.042705,14809.63046,0.15,182.9,0.100,0,...,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,0,81.838710
4,273,32.322705,24.2800,28.301352,8.042705,14809.63046,0.15,182.9,0.100,0,...,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,0,81.838710

In [24]:
# Columnas del datset Clima
# ==========================================
print("Cantidad de Registros : ", len(df_clima.shape))
df_clima.columns

Cantidad de Registros :  2

Index(['ID_EVENTO', 'Temp_Max_Avg_Veg', 'Temp_Min_Avg_Veg', 'Temp_Avg_Veg',
       'Diurnal_Range_Avg_Veg', 'Sol_Ener_Accu_Veg', 'Temp_Max_34_Freq_Veg',
       'Rain_Accu_Veg', 'Rain_10_Freq_Veg', 'Temp_Min_15_Freq_Veg',
       'Rhum_Avg_Veg', 'Temp_Max_Avg_For', 'Temp_Min_Avg_For', 'Temp_Avg_For',
       'Diurnal_Range_Avg_For', 'Sol_Ener_Accu_For', 'Temp_Max_34_Freq_For',
       'Rain_Accu_For', 'Rain_10_Freq_For', 'Temp_Min_15_Freq_For',
       'Rhum_Avg_For', 'Temp_Max_Avg_Mad', 'Temp_Min_Avg_Mad', 'Temp_Avg_Mad',
       'Diurnal_Range_Avg_Mad', 'Sol_Ener_Accu_Mad', 'Temp_Max_34_Freq_Mad',
       'Rain_Accu_Mad', 'Rain_10_Freq_Mad', 'Temp_Min_15_Freq_Mad',
       'Rhum_Avg_Mad'],
      dtype='object')

In [25]:
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_EVENTO              800 non-null    int64
 1   Temp_Max_Avg_Veg       800 non-null    float64
 2   Temp_Min_Avg_Veg       800 non-null    float64
 3   Temp_Avg_Veg           800 non-null    float64
 4   Diurnal_Range_Avg_Veg  800 non-null    float64
 5   Sol_Ener_Accu_Veg      800 non-null    float64
 6   Temp_Max_34_Freq_Veg   800 non-null    float64
 7   Rain_Accu_Veg          800 non-null    float64
 8   Rain_10_Freq_Veg       800 non-null    float64
 9   Temp_Min_15_Freq_Veg   800 non-null    int64
 10  Rhum_Avg_Veg           800 non-null    float64
 11  Temp_Max_Avg_For       800 non-null    float64
 12  Temp_Min_Avg_For       800 non-null    float64
 13  Temp_Avg_For           800 non-null    float64
 14  Diurnal_Range_Avg_For  800 non-null    float64
 15  Sol_Ener_Accu_For      800 non-null    float64
 16  Temp_Max_34_Freq_For   800 non-null    float64
 17  Rain_Accu_For          800 non-null    float64
 18  Rain_10_Freq_For       800 non-null    float64
 19  Temp_Min_15_Freq_For   800 non-null    int64
 20  Rhum_Avg_For           800 non-null    float64
 21  Temp_Max_Avg_Mad       800 non-null    float64
 22  Temp_Min_Avg_Mad       800 non-null    float64
 23  Temp_Avg_Mad           800 non-null    float64
 24  Diurnal_Range_Avg_Mad  800 non-null    float64
 25  Sol_Ener_Accu_Mad      800 non-null    float64
 26  Temp_Max_34_Freq_Mad   800 non-null    float64
 27  Rain_Accu_Mad          800 non-null    float64
 28  Rain_10_Freq_Mad       800 non-null    float64
 29  Temp_Min_15_Freq_Mad   800 non-null    int64
 30  Rhum_Avg_Mad           800 non-null    float64
dtypes: float64(27), int64(4)
memory usage: 193.9 KB

In [26]:
# Se realiza un mergue entre la matriz Final y datos del clima
# ============================================================
dataframe_final = pd.merge(matrizFinal,df_clima,how = 'inner', on=["ID_EVENTO"])

In [27]:
dataframe_final

,ID_EVENTO,ID_LOTE,TIPO_SIEMBRA,SEM_TRATADAS,MATERIAL_GENETICO,CULT_ANT,DRENAJE,METODO_COSECHA,ALMACENAMIENTO_FINCA,AREA,...,Temp_Max_Avg_Mad,Temp_Min_Avg_Mad,Temp_Avg_Mad,Diurnal_Range_Avg_Mad,Sol_Ener_Accu_Mad,Temp_Max_34_Freq_Mad,Rain_Accu_Mad,Rain_10_Freq_Mad,Temp_Min_15_Freq_Mad,Rhum_Avg_Mad
0,53,40,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,1.0,...,32.047671,23.602564,27.825117,8.445107,13197.57290,0.051282,279.3,0.230769,0,82.410256
1,54,43,Mecanizado,SI,DK 234,Maiz,SI,Manual,NO,1.0,...,32.372137,23.485714,27.928926,8.886423,12436.48772,0.028571,221.2,0.257143,0,81.857143
2,56,44,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,1.0,...,32.167009,23.533333,27.850171,8.633676,11267.16834,0.030303,226.0,0.272727,0,82.606061
3,57,45,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,1.0,...,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,0,81.838710
4,273,46,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,1.0,...,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,0,81.838710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,4671,4323,Manual,NO,Otro,Maiz,SI,Manual,NO,1.0,...,32.011148,22.521404,27.266276,9.489744,15024.03614,0.025641,248.2,0.153846,0,80.109595
793,4672,4322,Mecanizado,NO,Otro,Maiz,SI,Mecanizada,NO,2.1,...,32.137064,22.487064,27.312064,9.650000,16614.58589,0.047619,268.2,0.166667,0,79.995427
794,4673,4321,Mecanizado,NO,Otro,Algodón,NO,Mecanizada,NO,2.0,...,32.461599,22.506837,27.484218,9.954762,17147.13705,0.047619,179.2,0.142857,0,79.290078
795,4674,4320,Mecanizado,NO,DK 234 YGRR,Algodón,SI,Mecanizada,NO,2.2,...,32.462326,22.564958,27.513642,9.897368,15498.53974,0.052632,173.5,0.157895,0,79.227474
796,4675,4319,Mecanizado,NO,P3966 (Pioneer),Algodón,SI,Mecanizada,NO,2.3,...,32.462326,22.564958,27.513642,9.897368,15498.53974,0.052632,173.5,0.157895,0,79.227474

In [28]:
# Eliminamos Columnas Inicilamente por su alta varianza
borrarPorVarianza = ["ContEnfQui_Antes_Siem", "ContEnfQui_Siem_Eme","ContMalMec_Antes_Siem"
                    ,"FerOrg_Antes_Siem","FerOrg_Siem_Emer","porc_ArF","Temp_Min_15_Freq_Veg",
                    "Temp_Min_15_Freq_For","Temp_Min_15_Freq_Mad","AREA"]

In [29]:
# Se eliminan de la matriz Final las caracteristicas con alta varianza
dataframe_final = dataframe_final.drop(borrarPorVarianza,axis=1)

In [30]:
dataframe_final

,ID_EVENTO,ID_LOTE,TIPO_SIEMBRA,SEM_TRATADAS,MATERIAL_GENETICO,CULT_ANT,DRENAJE,METODO_COSECHA,ALMACENAMIENTO_FINCA,RDT_AJUSTADO,...,Rhum_Avg_For,Temp_Max_Avg_Mad,Temp_Min_Avg_Mad,Temp_Avg_Mad,Diurnal_Range_Avg_Mad,Sol_Ener_Accu_Mad,Temp_Max_34_Freq_Mad,Rain_Accu_Mad,Rain_10_Freq_Mad,Rhum_Avg_Mad
0,53,40,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,4767.441860,...,80.241379,32.047671,23.602564,27.825117,8.445107,13197.57290,0.051282,279.3,0.230769,82.410256
1,54,43,Mecanizado,SI,DK 234,Maiz,SI,Manual,NO,4651.162791,...,80.517241,32.372137,23.485714,27.928926,8.886423,12436.48772,0.028571,221.2,0.257143,81.857143
2,56,44,Mecanizado,NO,PIONEER 30F32,Algodón,SI,Manual,NO,5180.232558,...,80.327586,32.167009,23.533333,27.850171,8.633676,11267.16834,0.030303,226.0,0.272727,82.606061
3,57,45,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,4897.674419,...,80.517241,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,81.838710
4,273,46,Mecanizado,NO,Otro,Algodón,SI,Manual,NO,5302.325581,...,80.517241,32.187527,23.535484,27.861505,8.652043,11066.68328,0.032258,223.2,0.290323,81.838710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,4671,4323,Manual,NO,Otro,Maiz,SI,Manual,NO,6900.581395,...,78.631618,32.011148,22.521404,27.266276,9.489744,15024.03614,0.025641,248.2,0.153846,80.109595
793,4672,4322,Mecanizado,NO,Otro,Maiz,SI,Mecanizada,NO,5983.720930,...,78.794029,32.137064,22.487064,27.312064,9.650000,16614.58589,0.047619,268.2,0.166667,79.995427
794,4673,4321,Mecanizado,NO,Otro,Algodón,NO,Mecanizada,NO,6105.325581,...,78.764912,32.461599,22.506837,27.484218,9.954762,17147.13705,0.047619,179.2,0.142857,79.290078
795,4674,4320,Mecanizado,NO,DK 234 YGRR,Algodón,SI,Mecanizada,NO,6216.279070,...,78.961546,32.462326,22.564958,27.513642,9.897368,15498.53974,0.052632,173.5,0.157895,79.227474
796,4675,4319,Mecanizado,NO,P3966 (Pioneer),Algodón,SI,Mecanizada,NO,6140.465116,...,78.961546,32.462326,22.564958,27.513642,9.897368,15498.53974,0.052632,173.5,0.157895,79.227474